name: Test & Build

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [develop, feature/*, implement-terraform-configuration-with-aws]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run linting
      run: |
        cd frontend
        npm run lint
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    
    - name: Validate Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.0
    
    - name: Terraform Format Check
      run: |
        cd terraform
        terraform fmt -check
    
    - name: Terraform Validate
      run: |
        cd terraform
        terraform init -backend=false
        terraform validate